apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ${REPO_NAME}
spec:
  channel: ${CHANNEL}
  name: ${REPO_NAME}
  source: ${REPO_NAME}-registry
  sourceNamespace: ${NAMESPACE}
