apiVersion: monitoring.openshift.io/v1alpha1
kind: ClusterUrlMonitor
metadata:
  name: clusterurlmonitor-sample
spec:
  prefix: https://api.
  port: "6443"
  suffix: /
  slo:
    targetAvailabilityPercent: "99.5"
