---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: routemonitors.monitoring.openshift.io
spec:
  group: monitoring.openshift.io
  names:
    kind: RouteMonitor
    listKind: RouteMonitorList
    plural: routemonitors
    singular: routemonitor
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: RouteMonitor is the Schema for the routemonitors API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: RouteMonitorSpec defines the desired state of RouteMonitor
              properties:
                route:
                  description: RouteMonitorRouteSpec references the observed Route resource
                  properties:
                    name:
                      description: Name is the name of the Route
                      type: string
                    namespace:
                      description: Namespace is the namespace of the Route
                      type: string
                  type: object
                skipPrometheusRule:
                  description: SkipPrometheusRule instructs the controller to skip the
                    creation of PrometheusRule CRs. One common use-case for is for alerts
                    that are defined separately, such as for hosted clusters.
                  type: boolean
                slo:
                  description: SloSpec defines what is the percentage
                  properties:
                    targetAvailabilityPercent:
                      description: TargetAvailabilityPercent defines the percent number
                        to be used
                      type: string
                  required:
                    - targetAvailabilityPercent
                  type: object
              type: object
            status:
              description: RouteMonitorStatus defines the observed state of RouteMonitor
              properties:
                errorStatus:
                  type: string
                prometheusRuleRef:
                  description: NamespacedName contains the name of a object and its
                    namespace
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                    - name
                    - namespace
                  type: object
                routeURL:
                  description: RouteURL is the url extracted from the Route resource
                  type: string
                serviceMonitorRef:
                  description: NamespacedName contains the name of a object and its
                    namespace
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                    - name
                    - namespace
                  type: object
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}