---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  creationTimestamp: null
  name: clusterurlmonitors.monitoring.openshift.io
spec:
  group: monitoring.openshift.io
  names:
    kind: ClusterUrlMonitor
    listKind: ClusterUrlMonitorList
    plural: clusterurlmonitors
    singular: clusterurlmonitor
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ClusterUrlMonitor is the Schema for the clusterurlmonitors API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClusterUrlMonitorSpec defines the desired state of ClusterUrlMonitor
            properties:
              domainRef:
                default: infra
                description: ClusterDomainRef defines the object used determine the
                  cluster's domain By default, 'infra' is used, which references the
                  'infrastructures/cluster' object
                enum:
                - infra
                - hcp
                type: string
              port:
                type: string
              prefix:
                description: Foo is an example field of ClusterUrlMonitor. Edit ClusterUrlMonitor_types.go
                  to remove/update
                type: string
              slo:
                description: SloSpec defines what is the percentage
                properties:
                  targetAvailabilityPercent:
                    description: TargetAvailabilityPercent defines the percent number
                      to be used
                    type: string
                required:
                - targetAvailabilityPercent
                type: object
              suffix:
                type: string
            type: object
          status:
            description: ClusterUrlMonitorStatus defines the observed state of ClusterUrlMonitor
            properties:
              errorStatus:
                type: string
              prometheusRuleRef:
                description: NamespacedName contains the name of a object and its
                  namespace
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                - namespace
                type: object
              serviceMonitorRef:
                description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                  of cluster Important: Run "make" to regenerate code after modifying
                  this file'
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                - namespace
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
